require("prototypes.categories")
require("prototypes.entity")
require("prototypes.fluid")
require("prototypes.items.mod")
require("prototypes.recipes.mod")
require("prototypes.technology.mod")
require("prototypes.planets.mod")
require("prototypes.ambient-sounds")
